name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"] # Change to your default branch
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: true # <--- CRITICAL: This tells the runner to download the actual LFS files

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './html/' # Upload html directory (or your build folder if using a generator)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5